public class CourseArray {
	public static Course[] courses = {
			new Course("ART", 100, "Understanding Visual Culture"), 
			new Course("ART", 102, "Drawing for Non-Majors"), 
			new Course("ART", 103, "Painting for Non-Majors"), 
			new Course("ART", 104, "Sculpture for Non-Majors"), 
			new Course("ART", 105, "Visual Design for Non-Majors"), 
			new Course("ART", 140, "Introduction to ART"), 
			new Course("ART", 150, "Introduction to Drawing"), 
			new Course("ART", 151, "Black & White Film Photography"), 
			new Course("ART", 153, "Digital Photography Seminar"), 
			new Course("ART", 154, "Digital Video"), 
			new Course("ART", 155, "Introduction to Graphic Design - Unit One"), 
			new Course("ART", 199, "Undergraduate Open Seminar"), 
			new Course("ART", 201, "Art in Early Childhood"),
			new Course("ASTR", 100, "Introduction to Astronomy"),
			new Course("ASTR", 121, "Solar System and Worlds Beyond"),
			new Course("ASTR", 122, "Stars and Galaxies"),
			new Course("ASTR", 150, "Killer Skies: Astro-Disasters"),
			new Course("ASTR", 199, "Undergraduate Open Seminar"),
			new Course("ASTR", 210, "Introduction to Astrophysics"),
			new Course("ENG", 100, "Engineering Orientation"),
			new Course("ENG", 101, "Engineering at Illinois"),
			new Course("ENG", 198, "Special Topics"),
			new Course("ENG", 199, "Undergraduate Open Seminar"),
			new Course("ENG", 261, "Technology & Mgmt Seminar"),
			new Course("ENG", 298, "Special Topics"),
			new Course("ENG", 299, "Engineering Study Abroad"),
			new Course("BIOE", 120, "Introduction to Bioengineering"),
			new Course("BIOE", 199, "Undergraduate Open Seminar"),
			new Course("BIOE", 200, "Bioengineering Career Immersion"),
			new Course("BIOE", 201, "Conservation Principles Bioeng"),
			new Course("BIOE", 202, "Cell & Tissue Engineering Lab"),
			new Course("BIOE", 206, "Cellular Bioengineering"),
			new Course("BIOE", 220, "Bioenergetics"),
			new Course("BIOE", 297, "Individual Study"),
			new Course("BIOE", 298, "Special Topics"),
			new Course("CHEM", 101, "Introductory Chemistry"),
			new Course("CHEM", 102, "General Chemistry I"),
			new Course("CHEM", 103, "General Chemistry Lab I"),
			new Course("CHEM", 104, "General Chemistry II"),
			new Course("CHEM", 105, "General Chemistry Lab II"),
			new Course("CHEM", 197, "Individual Study Freshman"),
			new Course("CHEM", 199, "Undergraduate Open Seminar"),
			new Course("CHEM", 202, "Accelerated Chemistry I"),
			new Course("CHEM", 203, "Accelerated Chemistry Lab I"),
			new Course("CHEM", 222, "Quantitative Analysis Lecture"),
			new Course("CHEM", 223, "Quantitative Analysis Lab"),
			new Course("CHEM", 232, "Elementary Organic Chemistry I"),
			new Course("CHEM", 233, "Elementary Organic Chem Lab I"),
			new Course("CHEM", 236, "Fundamental Organic Chem I"),
			new Course("CHEM", 237, "Structure and Synthesis"),
			new Course("CHEM", 293, "Cooperative Education Practice"),
			new Course("CHEM", 295, "Chemistry Internship"),
			new Course("CHEM", 297, "Individual Study Sophomore"),
			new Course("CS", 100, "Freshman Orientation"),
			new Course("CS", 101, "Intro Computing: Engrg & Sci"),
			new Course("CS", 105, "Intro Computing: Non-Tech"),
			new Course("CS", 125, "Intro to Computer Science"),
			new Course("CS", 126, "Software Design Studio"),
			new Course("CS", 173, "Discrete Structures"),
			new Course("CS", 196, "Freshman Honors"),
			new Course("CS", 199, "Undergraduate Open Seminar in Computer Science"),
			new Course("CS", 210, "Ethical & Professional Issues"),
			new Course("CS", 225, "Data Structures"),
			new Course("CS", 233, "Computer Architecture"),
			new Course("CS", 241, "System Programming"),
			new Course("CS", 242, "Programming Studio"),
			new Course("CS", 296, "Honors Course"),
			new Course("ECON", 102, "Microeconomic Principles"),
			new Course("ECON", 103, "Macroeconomic Principles"),
			new Course("ECON", 198, "Economics at Illinois"),
			new Course("ECON", 199, "Undergraduate Open Seminar"),
			new Course("ECON", 202, "Economic Statistics I"),
			new Course("ECON", 203, "Economic Statistics II"),
			new Course("ECON", 210, "Environmental Economics"),
			new Course("ECON", 220, "Intl Economic Principles"),
			new Course("LAW", 199, "Undergraduate Open Seminar"),
			new Course("MATH", 101, "Thinking Mathematically"),
			new Course("MATH", 103, "Theory of Arithmetic"),
			new Course("MATH", 112, "Algebra"),
			new Course("MATH", 115, "Preparation for Calculus"),
			new Course("MATH", 119, "Ideas in Geometry"),
			new Course("MATH", 124, "Finite Mathematics"),
			new Course("MATH", 125, "Elementary Linear Algebra"),
			new Course("MATH", 181, "A Mathematical World"),
			new Course("MATH", 199, "Undergraduate Open Seminar"),
			new Course("MATH", 210, "Theory of Interest"),
			new Course("MATH", 213, "Basic Discrete Mathematics"),
			new Course("MATH", 220, "Calculus"),
			new Course("MATH", 221, "Calculus I"),
			new Course("MATH", 225, "Introductory Matrix Theory"),
			new Course("MATH", 231, "Calculus II"),
			new Course("MATH", 241, "Calculus III"),
			new Course("MATH", 285, "Intro Differential Equations"),
			new Course("MATH", 286, "Intro to Differential Eq Plus"),
			new Course("MATH", 299, "Topics in Mathematics"),
			new Course("PHYS", 100, "Thinking About Physics"),
			new Course("PHYS", 101, "College Physics: Mech & Heat"),
			new Course("PHYS", 102, "College Physics: E&M & Modern"),
			new Course("PHYS", 110, "Physics Careers"),
			new Course("PHYS", 150, "Physics of Societal Issues"),
			new Course("PHYS", 199, "Undergraduate Open Seminar"),
			new Course("PHYS", 211, "University Physics: Mechanics"),
			new Course("PHYS", 212, "University Physics: Elec & Mag"),
			new Course("PHYS", 213, "Univ Physics: Thermal Physics"),
			new Course("PHYS", 214, "Univ Physics: Quantum Physics"),
			new Course("PHYS", 222, "Enrichment E & M"),
			new Course("PHYS", 225, "Relativity & Math Applications"),
			new Course("PHYS", 298, "Freshmen/Sophomore Special Topics in Physics")
		};
}
